language: python
python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
install: python setup.py develop
script: ./runtests.sh
notifications:
    irc:
        - "irc.freenode.net#threebean"
    on_success: never
    on_failure: always
